name: go echo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.set-output.outputs.name }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: build
        run: go build .
      - name: run
        id: set-output
        run: ./go-workflow-test
      - name: echo
        run: echo ${{ steps.set-output.outputs.name }}